language: node_js
node_js:
 - "12"

cache: npm

script:
  - npm run lint
  - npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: dist
 fqdn: recover.coin.space
 on:
   branch: master
